/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function basic(content: string): number | null
export interface JsPosition {
  line: number
  character: number
}
export class NodejsLspFiles {
  constructor()
  /** Actions can come from unsaved context. */
  addGlobalContext(actions?: Array<string> | undefined | null): void
  deleteAll(): void
  addOne(id: number, content: string, line: number): boolean
  hover(position: JsPosition, id: number): void
  static complete(position: JsPosition, id: number, content: string): void
  gotoDefinition(position: JsPosition, id: number): void
}
