name: build-extension

on: [workflow_dispatch, workflow_call]


env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:


      - name: Get latest release version
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "Latest release is: $LATEST_TAG"        
          echo "LATEST_TAG=$LATEST_TAG"
          echo "version=$LATEST_TAG" >> $GITHUB_ENV          
          

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Download binaries
        run: |
          mkdir -p binaries extensions
          gh release download "${{ env.version }}" \
            --pattern "jinja-lsp-*" \
            --dir binaries

      - name: Npm install
        run: |
          npm install
          npm install @vscode/vsce -g
          npm install vscode-languageclient
        working-directory: editors/code
        
      - name: Build extensions
        run: |
          bash build_vsix.sh
        working-directory: editors/code

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jinja-lsp-extension
          path: ./extensions
