name: release-extension

on:
  workflow_run:
    workflows: ["Build & Release"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-extension.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download built extensions
        uses: actions/download-artifact@v4
        with:
          name: jinja-lsp-extension
          path: ./extensions

      - name: Publish extensions
        run: |
          for vsix in ./extensions/*.vsix; do
            npx @vscode/vsce publish --pat ${{ secrets.VSCODE_TOKEN }} --packagePath "$vsix"
            npx ovsx publish --pat ${{ secrets.OPEN_VSX_TOKEN }} --packagePath "$vsix"
          done
