name: Build & Release

# on:
#   push:
#     branches: ["main"]


on:
  workflow_dispatch  

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            use: cargo
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
            use: zigbuild
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            use: zigbuild
          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04
            use: zigbuild
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-22.04
            use: zigbuild
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-22.04
            use: zigbuild
          - target: riscv64gc-unknown-linux-gnu
            os: ubuntu-22.04
            use: zigbuild
          - target: x86_64-unknown-freebsd
            os: ubuntu-22.04
            use: zigbuild
          - target: aarch64-linux-android
            os: ubuntu-22.04
            use: zigbuild
          - target: armv7-linux-androideabi
            os: ubuntu-22.04
            use: zigbuild
          - target: x86_64-pc-windows-msvc
            os: windows-2022
            use: cargo
          - target: aarch64-pc-windows-msvc
            os: windows-2022
            use: cargo
          - target: i686-pc-windows-msvc
            os: windows-2022
            use: cargo
          - target: x86_64-apple-darwin
            os: macos-latest
            use: cargo
          - target: aarch64-apple-darwin
            os: macos-latest
            use: cargo
          - target: universal-apple-darwin
            os: macos-latest
            use: universal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-zigbuild
        if: ${{ matrix.use == 'zigbuild' }}
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-zigbuild

      - name: Build with cargo-zigbuild
        if: ${{ matrix.use == 'zigbuild' }}
        run: cargo zigbuild --release --target ${{ matrix.target }}

      - name: Build with cargo
        if: ${{ matrix.use == 'cargo' }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build universal macOS binary
        if: ${{ matrix.use == 'universal' }}
        run: |
          rustup target add x86_64-apple-darwin aarch64-apple-darwin
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
          mkdir -p "target/${{ matrix.target }}/release"
          lipo -create -output "target/${{ matrix.target }}/release/jinja-lsp" \
            target/x86_64-apple-darwin/release/jinja-lsp \
            target/aarch64-apple-darwin/release/jinja-lsp

      - name: Rename binary
        shell: bash
        run: |
          binary_name="jinja-lsp-${{ matrix.target }}"
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            binary_name="${binary_name}.exe"
          fi
          mkdir -p staged
          cp target/${{ matrix.target }}/release/jinja-lsp* staged/"${binary_name}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: staged/*

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if release should be created
        shell: bash
        run: |
          set -o pipefail

          RELEASE_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)
          OLD_VERSION=$( curl -s --fail-with-body https://api.github.com/repos/uros-5/jinja-lsp/releases/latest | jq -r '.tag_name' )

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"
          echo "$OLD_VERSION -> $RELEASE_VERSION"

          if [[ "$RELEASE_VERSION" == "$OLD_VERSION" ]] || ! [[ "$OLD_VERSION" =~ ^[0-9]\.[0-9]\.[0-9]$ ]]; then
            echo "SHOULD_RELEASE=no" >> "$GITHUB_ENV"
          else
            git tag "$RELEASE_VERSION"
            git push -u origin "$RELEASE_VERSION"
            echo "SHOULD_RELEASE=yes" >> "$GITHUB_ENV"
          fi

      - name: Download all binaries
        uses: actions/download-artifact@v4
        if: env.SHOULD_RELEASE == 'yes'
        with:
          path: binaries

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: env.SHOULD_RELEASE == 'yes'
        with:
          files: binaries/*/*
          tag_name: ${{ env.RELEASE_VERSION }}
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
